### ISSUE TITLE
PROYECTO PULSADOR 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/proyecto-pulsador-equipo-saul-lopez-bautista#1]
[Reporte de diseño de circuito.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-pulsador-equipo-saul-lopez-bautista/files/7805472/Reporte.de.diseno.de.circuito.pdf)

**Comment by josealfredo79** [comment]
Revisado
