### ISSUE TITLE
proyecto de pulsador

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/proyecto-pulsador-equipo-saul-lopez-bautista#3]
[Proyecto-pulsador.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-pulsador-equipo-saul-lopez-bautista/files/7819357/Proyecto-pulsador.pdf)

**Comment by josealfredo79** [comment]
Falto el circuito en físico
